import { Inter } from "next/font/google";
import "./globals.css";
import App from "./App";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://site-assets.fontawesome.com/releases/v6.5.1/css/all.css"
        />
      </head>
      <body className={inter.className}>
        <App>{children}</App>
      </body>
    </html>
  );
}
